version: '2'
services:
  mysqlpetclinic:
    image: mysql:5.7
    container_name: mysqlpetclinic
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"


  spring-petclinic:
    image: st251/petclinic:44
    container_name: spring-petclinic
    mem_limit: 512M
    depends_on:
      - mysqlpetclinic
    ports:
     - 8181:8181
    environment:
     - SPRING_PROFILES_ACTIVE=mysql
 
